common/urls.py
from common.views import index, RegisterView, CreateUserProfile
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.urls import path
from django.urls import include
from allauth.account.views import login, logout #стандартные авторизационные отбработчики

app_name = 'common'  
urlpatterns = [    
	path('login/', login, name='login'),  
	path('logout/', logout, name='logout'),
	
	path('', index, name='index'),
	
	# path('login/', LoginView.as_view(template_name='common/login.html'), name='login'), 
	# path('logout/', LogoutView.as_view(), name='logout'),
	
	path('register/', RegisterView.as_view(
		template_name='common/register.html',
		success_url=reverse_lazy('common:profile-create')
    ), name='register'),
	path('profile-create/', CreateUserProfile.as_view(template_name = 'common/profile-create.html'), name='profile-create'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include  
from p_library.views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many, FriendList, FriendEdit, friends_books, BookList, book_edit, books_list, book_increment, book_decrement, publishing, index

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', namespace='common')), # пути приложения с профилями пользователя
    path('accounts/', include('allauth.urls')),
    # path('', books_list), # books_list - метод, который будет исполнятся при запросе URL в первом аргументе
    path('index/', index, name='all_book'),
    path('index/book_increment/', book_increment),
    path('index/book_decrement/', book_decrement),
    path('index/publishing/', publishing),
    path('author/create', AuthorEdit.as_view(), name='author_create'),
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', books_authors_create_many, name='author_book_create_many'), #books_authors_create_many вызываем метод из файла view.py
    path('friends/', FriendList.as_view(), name='friend_list'), # выводим список друзей и переходим в форму создания друга и форму выдачи книг друзьям
    path('friend/create', FriendEdit.as_view(), name='friend_create'), # формма создания друга
    path('friends/books', friends_books, name='friends_books'), # формма создания друга
    path('books', BookList.as_view(), name='books_list'), # форма просмотра всех книг с уточнением, у кого книга. 
    path('book/edit/<int:book_id>/', book_edit, name='book_edit'), # форма редактирования книги, можно отдать книгу другу
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # для статических медиа файлов
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # для файлов стилей

common/models.py
from django.db import models
from django.contrib.auth.models import User  
  
  
class UserProfile(models.Model):
    age = models.IntegerField()
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    def __str__(self):
        return self.user.username

common/forms.py
from django import forms
from common.models import UserProfile

class ProfileCreationForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['age']

common/views.py
from django.shortcuts import render
from django.views.generic import FormView  
from django.contrib.auth.forms import UserCreationForm  
from django.contrib.auth import login, authenticate  
from common.forms import ProfileCreationForm  
from django.http.response import HttpResponseRedirect  
from django.urls import reverse_lazy  
from common.models import UserProfile
from allauth.socialaccount.models import SocialAccount

class RegisterView(FormView):
    form_class = UserCreationForm
    template_name = 'common/register.html'

# переопределяем form_valid, чтобы после регистрации перенаправить
# на форму заполнения профиля
    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')
        login(self.request, authenticate(username=username, password=raw_password))
        return super(RegisterView, self).form_valid(form)

class CreateUserProfile(FormView):
    
    form_class = ProfileCreationForm
    template_name = 'common/profile-create.html'
    success_url = reverse_lazy('books_list')
    # success_url = reverse_lazy('common:index')
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse_lazy('common:login'))
        return super(CreateUserProfile, self).dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.user = self.request.user
        instance.save()
        return super(CreateUserProfile, self).form_valid(form)

def index(request):  
    context = {}  
    print('request.user', request.user)
    if request.user.is_authenticated:  
        context['username'] = request.user.username
        try:
            context['age'] = UserProfile.objects.get(user=request.user).age
        except UserProfile.DoesNotExist:
            context['github_url'] = SocialAccount.objects.get(provider='github', user=request.user).extra_data['html_url']
            print('github_url', context['github_url'])
            print('Поймали ошибку')
        except SocialAccount.DoesNotExist:
            pass
    return render(request, 'common/index.html', context)

common/templates/common/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">
 <link rel="icon" href="data:;base64,=">
 
 {% block list_header %}
 <title>My_Library</title> 
 {% endblock %}

 <meta name="viewport" content="width=device-width, initial-scale=1.0">

 {% load static %}
 {% block bootstrap_header %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
 {% endblock %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"> 
</head>  
<body>
    {% if user.is_authenticated %}
        <p class="text-white"><a class="nav-link" href="{% url 'account_logout' %}" class="a-header"> Log Out</a></p>
        {% else %}
        <p class="my-btn"><a class="nav-link" href="{% url 'account_login' %}" class="a-header"> Log In</a></p>
        <p class="my-btn"><a href="{% url 'common:register' %}" class="a-header"> Registration</a></p>
     {% endif %}
    {% block contentall %}
    {% endblock %}
</body> 
</html>

common/templates/common/index.html
{% extends 'base.html' %}

{% block list_header %}
    <title>Главная страница</title>
{% endblock %}

{% block content %}
<!-- <p>Войти с помощью <a href="accounts/github/login/">GitHub</a></p> -->
{% if user.is_authenticated %}  
    <h1 class="page-header">Привет, {{ username }}!
        {% if age %}
        Я знаю, что тебе {{ age }} лет
        {% else %}
        Я знаю, что тебе &lt;возраст не указан &gt; лет
        {% endif %}
    </h1>
    <div class="row">
        {% if github_url %}
        <p>Я знаю твой профиль на <a href="{{ github_url }}">github</a>!</p><br />
        {% endif %}
        <p>Тут ты можешь <a href="logout">выйти</a> или перейти на <a href="login"> сайт библиотеки. </p> 
    </div>
{% else %}
    <p>Тебе нужно <a href="register/">зарегистрироваться</a> или <a href="login">войти на сайт</a>!</p>
{% endif %}
{% endblock %}

common/templates/common/login.html
{% extends 'common/base.html' %}

{% block list_header %}
	<title>Войти</title>
{% endblock %}

{% block contentall %}
<h3 class="page-header">Страница логина</h3>
<form method="post">  
	{% csrf_token %}  
	{{ form.as_ul }}  
	<input type="submit" value="Войти">  
</form>
{% endblock %}

common/templates/common/profile-create.html
{% extends 'base.html' %}

{% block list_header %}
<meta name="viewport"  
content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">  
<meta http-equiv="X-UA-Compatible" content="ie=edge">
 <title>Создание профайла</title>
{% endblock %}

{% block contentall %}
<h3 class="page-header">Страница регистрации</h3>
<form method="post">

  {% csrf_token %}  
    {{ form.as_ul }}  
    <input type="submit" value="Создание профиля">  
</form> 
{% endblock %}

common/templates/common/register.html
{% extends 'base.html' %}

{% block list_header %}
<meta name="viewport"  
  content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">  
 <meta http-equiv="X-UA-Compatible" content="ie=edge">  
	<title>Регистрация</title>
{% endblock %}

{% block contentall %}
<h4 class="page-header">Страница регистрации</h3>
<form method="post">  
  {% csrf_token %}  
    {{ form.as_ul }}  
    <input type="submit" value="Зарегистрироваться">  
</form> 
{% endblock %}