common/urls.py
from common.views import index, RegisterView, CreateUserProfile
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.urls import path
from django.urls import include
from allauth.account.views import login, logout #стандартные авторизационные отбработчики

app_name = 'common'  
urlpatterns = [    
	path('login/', login, name='login'),  
	path('logout/', logout, name='logout'),
	
	path('', index, name='index'),
	
	# path('login/', LoginView.as_view(template_name='common/login.html'), name='login'), 
	# path('logout/', LogoutView.as_view(), name='logout'),
	
	path('register/', RegisterView.as_view(
		template_name='common/register.html',
		success_url=reverse_lazy('common:profile-create')
    ), name='register'),
	path('profile-create/', CreateUserProfile.as_view(template_name = 'common/profile-create.html'), name='profile-create'),
]

my_site/urls.py
from django.contrib import admin
from django.urls import path, include  
from p_library.views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many, FriendList, FriendEdit, friends_books, BookList, book_edit, books_list, book_increment, book_decrement, publishing, index

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls', namespace='common')), # пути приложения с профилями пользователя
    path('accounts/', include('allauth.urls')),
    # path('', books_list), # books_list - метод, который будет исполнятся при запросе URL в первом аргументе
    path('index/', index, name='all_book'),
    path('index/book_increment/', book_increment),
    path('index/book_decrement/', book_decrement),
    path('index/publishing/', publishing),
    path('author/create', AuthorEdit.as_view(), name='author_create'),
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', books_authors_create_many, name='author_book_create_many'), #books_authors_create_many вызываем метод из файла view.py
    path('friends/', FriendList.as_view(), name='friend_list'), # выводим список друзей и переходим в форму создания друга и форму выдачи книг друзьям
    path('friend/create', FriendEdit.as_view(), name='friend_create'), # формма создания друга
    path('friends/books', friends_books, name='friends_books'), # формма создания друга
    path('books', BookList.as_view(), name='books_list'), # форма просмотра всех книг с уточнением, у кого книга. 
    path('book/edit/<int:book_id>/', book_edit, name='book_edit'), # форма редактирования книги, можно отдать книгу другу
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # для статических медиа файлов
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # для файлов стилей

p_library/models.py
from django.db import models
from django.contrib.auth.models import User #стандартная модель пользователя

class Author(models.Model):  
    full_name = models.TextField(verbose_name=("Имя автора"))  
    birth_year = models.SmallIntegerField(null=True, verbose_name=("Год рождения"))  
    country = models.CharField(max_length=50, null=True, verbose_name=("Страна")) 
    
    def __str__ (self):
        return self.full_name

class Publishing(models.Model): 
    name = models.TextField(verbose_name=("Название"))   
    year_foundation = models.SmallIntegerField(verbose_name=("Год основания")) 
    
    def __str__ (self):
        return self.name

#  модель друга
class Friend(models.Model):
    FIO = models.CharField(max_length=100, verbose_name=("ФИО Друга"))
    PhoneNumber = models.CharField(max_length=20, verbose_name=("Номер телефона"))

    def __str__(self):
        return self.FIO

class Book(models.Model):  
    ISBN = models.CharField(max_length=13, null=True, verbose_name=("Международный стандартный книжный номер"))  
    description = models.TextField(verbose_name=("Описание"))  
    year_release = models.SmallIntegerField(verbose_name=("Дата выпуска"))  
    copy_count = models.IntegerField(default=1, verbose_name=("Количесвто копий"))
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name=("Цена")) 
    title = models.CharField(max_length=128, verbose_name=("Название книги"))
    publishing = models.ForeignKey(Publishing, on_delete=models.CASCADE, related_name='book_publishing', null=True, blank=True, verbose_name=("Издательство"))
    authors = models.ManyToManyField(
        Author,
        through='Inspiration',
        through_fields=('book', 'author'),
        verbose_name=('Авторы'),
    )
    friend = models.ForeignKey(Friend, related_name="friend_books", related_query_name="friend_book",
                                        on_delete=models.SET_NULL, null=True, blank=True, verbose_name=("Одолжил друг"))
    cover = models.ImageField(upload_to='user_cover/%Y/%m/%d', blank=True, verbose_name='Обложка книги') # обложка книги

    def __str__(self):
        return self.title

# вдохновитель inspirer для автора author при написании книги book
class Inspiration(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    inspirer = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        related_name="inspired_works",
        null=True,
    )
    

p_library/forms.py
from django import forms  
from p_library.models import Author, Book, Friend
from django.forms import formset_factory   
  
class AuthorForm(forms.ModelForm):  
    full_name = forms.CharField(widget=forms.TextInput) #вместо стандартного виджета будет использоваться виджет input type=text
    
    class Meta:  
        model = Author  
        fields = '__all__'

class BookForm(forms.ModelForm):  
    class Meta:  
        model = Book  
        fields = '__all__'

class FriendForm(forms.ModelForm):  
    class Meta:  
        model = Friend  
        fields = '__all__'

p_library/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy
from django.forms import formset_factory  #для работы с множеством форм на странице
from django.http.response import HttpResponseRedirect

from p_library.models import Book, Publishing, Author, Friend
from p_library.forms import AuthorForm, FriendForm, BookForm

def index(request):
    template = loader.get_template('index.html')
    books_count = Book.objects.all().count()
    books = Book.objects.all().order_by('publishing')
    books.order_by('publishing')
    arr = [i for i in range(1, 101)]
    biblio_data = {
        "title": "мою библиотеку",
        "books_count": books_count,
        "books": books,
        "arr": arr,
    }
    return HttpResponse(template.render(biblio_data, request)) #requestдобавлен в рендеринг, чтобы при открытии сайта в форму добавится CSRF

def books_list(request):
    books = Book.objects.all()
    return HttpResponse(books)

def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            book.copy_count += 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/index/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/index/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/index/')
    else:
        return redirect('/index/')

def publishing(request):
    template = loader.get_template('publishing.html')
    publishing = Publishing.objects.all()
    publishing_data = {
        "publishing": publishing,
    }
    return HttpResponse(template.render(publishing_data))


class AuthorEdit(CreateView):  
    model = Author  
    form_class = AuthorForm  
    # success_url = reverse_lazy('p_library:author_list')
    success_url = reverse_lazy('author_list')
    template_name = 'author_edit.html'  
    
class AuthorList(ListView):  
    model = Author  
    template_name = 'authors_list.html'

#форма создния друзей
class FriendEdit(CreateView):  
    model = Friend  
    form_class = FriendForm  
    success_url = reverse_lazy('friend_list')
    template_name = 'friends_edit.html'

class FriendList(ListView):  
    model = Friend 
    success_url = reverse_lazy('friends_books') #в случае успеха перенаправляем на страницу друзей и книг
    template_name = 'friends_list.html'
#   
class BookList(ListView):
    model = Book
    template_name = 'books_list.html'

def author_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  #  Первым делом, получим класс, который будет создавать наши формы. Обратите внимание на параметр `extra`, в данном случае он равен двум, это значит, что на странице с несколькими формами изначально будет появляться 2 формы создания авторов.
    if request.method == 'POST':  #  Наш обработчик будет обрабатывать и GET и POST запросы. POST запрос будет содержать в себе уже заполненные данные формы
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  #  Здесь мы заполняем формы формсета теми данными, которые пришли в запросе. Обратите внимание на параметр `prefix`.Мы можем иметь на странице не только несколько форм, но и разных формсетов, этот параметр позволяет их отличать в запросе.
        if author_formset.is_valid():  #  Проверяем, валидны ли данные формы
            for author_form in author_formset:  
                author_form.save()  #  Сохраним каждую форму в формсете
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  #  После чего, переадресуем браузер на список всех авторов.
    else:  #  Если обработчик получил GET запрос, значит в ответ нужно просто "нарисовать" формы.
        author_formset = AuthorFormSet(prefix='authors')  #  Инициализируем формсет и ниже передаём его в контекст шаблона.
    context = {'author_formset': author_formset} # обязательно должен быть словать
    return render(request, 'manage_authors.html', context)

def books_authors_create_many(request):  
    AuthorFormSet = formset_factory(AuthorForm, extra=2)  
    BookFormSet = formset_factory(BookForm, extra=2)  
    if request.method == 'POST':  
        author_formset = AuthorFormSet(request.POST, request.FILES, prefix='authors')  
        book_formset = BookFormSet(request.POST, request.FILES, prefix='books')  
        if author_formset.is_valid() and book_formset.is_valid():  
            for author_form in author_formset:  
                author_form.save()  
            for book_form in book_formset:  
                book_form.save()  
            return HttpResponseRedirect(reverse_lazy('p_library:author_list'))  
    else:  
        author_formset = AuthorFormSet(prefix='authors')  
        book_formset = BookFormSet(prefix='books')  
    return render(
	    request,  
		'manage_books_authors.html',  
		{  
	        'author_formset': author_formset,  
			'book_formset': book_formset,  
		}  
	)

def friends_books(request):
    fr = Friend.objects.all()
    all_books = Book.objects.all()
    # if request.method != 'POST':
    #     fr = Friend.objects.all()
    context = {'fr': fr, 'all_books' : all_books}
    return render(request, 'manage_friend_books.html', context)

def book_edit(request, book_id):
    """ редактируем книгу """
    book = Book.objects.get(id=book_id)
    fr = book.friend # ссылка на друга по внешнему ключу

    if request.method != 'POST':
        form = BookForm(instance=book) # ссылка на друга по внешнему ключу
    else:
        form = BookForm(instance=book, data = request.POST)
        if form.is_valid():
            form.save()
            return redirect('books_list')
    # вывести пустую или недействительную форму
    context = {'book': book, 'fr': fr, 'form' : form }
    return render(request, 'edit_book.html', context)

p_library/templates/author_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">  
	<title>Форма создания и редактирования Авторов</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить">  
</form>  
</body>  
</html>

p_library/templates/authors_list.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Список авторов</title>
</head>
<body>
	<ul>
		{% for author in object_list %}
		    <li>{{ author.full_name }}</li>
		{% endfor %}
	</ul>
</body>
</html>

p_library/templates/base.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">

 {% block list_header %}
 <title>My_Library</title> 
 {% endblock %}

 <meta name="viewport" content="width=device-width, initial-scale=1.0">

 {% load static %}
 {% block bootstrap_header %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
 {% endblock %}
 <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
 <link rel="icon" href="data:;base64,=">
</head>  
<body>
    <div class="page-header">
        <!-- <h1><a href="/" class="a-header">My personal library</a></h1> -->
        {% if user.is_authenticated %}
        <p><a href="{% url 'common:logout' %}" class="a-header"> Log Out</a></p>
        
        
        <h2><a href="{% url 'all_book' %}" class="a-header">My personal library</a></h2>
        <h5><a href="{% url 'friend_list' %}" class="a-header"> My friends <a href="{% url 'books_list' %}" class="a-header">My books</a></h5>
        
        {% else %}
        <p><a href="{% url 'common:login' %}" class="a-header"> Log In</a></p>
        <h2><a href="{% url 'common:index' %}" class="a-header">My personal library</a></h2>
        {% endif %}

    </div>
    <div class="content container">
        <div class="row">
            
            <div class="col-md-10">
            {% block my_h3 %}
            {% endblock %}
            
            {% block content %}
            {% endblock %}
            </div>
            {% block contentall %}
            {% endblock %}

        </div>
    </div>
</body> 
</html>

p_library/templates/books_list.html
{% extends 'base.html' %}
<!-- {%load staticfiles%} -->
	<!-- <a class="btn btn-outline-info" href="{% url 'friend_list' %}">Список друзей</a> -->
	{% block my_h3 %}
	<h3 class="my-h3">Мои книги</h3>
	{% endblock %}

	{% block content %}
	<ul class="list-group list-group-item-info">
		{% for book in object_list %}
		<li class="list-group-item">
			{% if book.cover %}
				<img src="{{ MEDIA_URL }}{{ book.cover }}" width="100" height="50" alt="обложка книги"/>
			{% endif %}
			
			<strong>{{ book.title }}</strong>
			{% if book.friend %}
					<br /> <p class="font-italic">Книга на руках у друга по имени 
								<strong>{{ book.friend.FIO }}</strong> </p>
				{% endif %}
				<p>
					<a class="text-info" href="{% url 'book_edit' book.id %}">Редактировать</a>
				</p>
			</li>
		{% endfor %}
	</ul>
	
{% endblock %}

p_library/templates/edit_book.html
{% load static %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
	<meta charset="UTF-8">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
	<title>Редактирование книги</title>  
</head>  
<body>  
<form action="{% url 'book_edit' book.id %}" method="post">  
	{% csrf_token %}  
	{{ form.as_p }}  
	<input type="submit" value="Сохранить">  
</form>  
</body>  
</html>

p_library/templates/friends_edit.html
{% extends 'base.html' %}

{% block list_header %}
<title>Форма создания и редактирования Друзей</title>  
{% endblock %}

{% block contentall %}
<form method="post">  
	{% csrf_token %}
	{{ form.as_p }}  
	<input type="submit" value="Сохранить нового друга">
</form>  
{% endblock %}

p_library/templates/friends_list.html
{% extends 'base.html' %}
{% block my_h3 %}
	<h3 class="my-h3">Мои друзья</h3>
{% endblock %}

{% block content %}
	<ul class="list-group list-group-item-info">
		{% for friend in object_list %}
		<li class="list-group-item">{{ friend.FIO }}, номер телефона: {{ friend.PhoneNumber }}</li>
		{% endfor %}
	</ul>
	<br>
	<p><a class="btn btn-outline-info my-btn" href="{% url 'friends_books' %}">Просмотреть, у кого мои книги</a></p>
	<p><a class="btn btn-outline-info my-btn" href="{% url 'friend_create' %}">Добавить друга</a></p>
{% endblock %}

p_library/templates/index.html
{% extends 'base.html' %}

{% load static %}
{% block contentall %}
<h3 class="my-h3 col-12"> Добро пожаловать в {{ title }} <br>
    <small>Тут собрано {{ books|length }} книг из моей личной коллекции.</small>
</h3>

<table class="table table-bordered">
    <tbody>
    {% for book in books %}
    <tr class="table-light">
        <td>{{ forloop.counter }}</td> <!-- новый столбец по заданию D4.5-->
        <td>{{ book.title }}</td>
        <td>{{ book.ISBN }}</td>
        <td>{{ book.description }}</td>
        <td>{{ book.year_release }}</td>
        <td>{{ book.author.full_name }}</td>
        <td>{{ book.author.country }}</td>
        <td>{{ book.copy_count }}</td>
        <td>
            <form action="/index/book_increment/" method="post" enctype="multipart/form-data">
                {% csrf_token %} <!-- CSRF-токен для защиты нашего сайта от сторонних атак. -->
                <input type="hidden" name="id" value="{{book.id}}" />
                <input type="submit" value="Увеличить кол-во" class="my-btn"/>
            </form>
            <form action="/index/book_decrement/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{book.id}}" />
                <input type="submit" value="Уменьшить кол-во" class="my-btn"/>
            </form>
        </td>
    </tr>
    {% endfor %}
</tbody>
</table>
<p> <!-- для D4.5-->
    {% for i in arr %}
        {% if i|divisibleby:"3" %}
            {{ i }}
        {% endif %}
    {% endfor %}
</p>
{% endblock %}

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple authors</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{% for form in author_formset %}
		{{ form.as_ul }}<!-- форма будет представлена в виде маркированного списка -->
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple Authors and Books</title>  
</head>  
<body>  
<form method="post">  
  {% csrf_token %}  
  {% for form in author_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
  
    {% for form in book_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_friend_books.html
{% extends 'base.html' %}

<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
 <title>Friend and Books</title>  
</head>  
<body>
  {% block my_h3 %}
	<h3 class="my-h3">У кого мои книги</h3>
  {% endblock %}  
  {% block content %}
  <ul class="list-group list-group-item-info">
    {% for ob_fr in fr %}
    <li class="list-group-item"><strong>{{ ob_fr.FIO }}</strong></li>
    <ul class="list-group">
      {% for book in ob_fr.friend_books.all %}
        <li class="list-group-item"> Книга: {{ book.title }} </li>
      {% empty %}
      <li class="list-group-item">не брал книги</li>
      {% endfor %} 
    </ul>
    {% endfor %} 
  </ul>
  <br>
  <!-- <p><a class="btn btn-outline-info my-btn" href="{% url 'friend_list' %}">Список друзей</a></p> -->
  <p><a class="btn btn-outline-info my-btn" href="{% url 'books_list' %}">Просмотреть/Редактировать выдачу книг</a></p>
</body>
  {% endblock %}

p_library/templates/publishing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
    {% for pub in publishing %}
    <ul class="list-group">
        <li class="list-group-item list-group-item-info"> 
            {{ pub.name }}
            <ul class="list-group">
                {% for book in pub.book_publishing.all %}
                <li class="list-group-item list-group-item-dark"> {{ book.title }} </li>
                {% endfor %}
            </ul>
        </li>
    </ul>
    {% endfor %}
</body>
</html>